#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         3
bspc config window_gap          12
bspc config top_padding 	26

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color \#ff2000

bspc config pointer_action1 move
bspc config pointer_action2 resize_side 
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# My adds
setxkbmap es
xset r rate 200

picom --config $HOME/.config/picom/picom.conf &
polybar -r bar &
xrandr --output Virtual1 --mode 1600x900
sleep 1
feh --bg-scale $HOME/Downloads/pexels-jvdm-1564839.jpg
